version: '3.8'

services:
  gestionrecursoshumanosapi:
    build:
      context: ./GestionRecursosHumanos.API
      dockerfile: Dockerfile
    ports:
      - "7229:80"
    environment:
      - "MongoDB__ConnectionString=mongodb://mongodb:27017"
      - "MongoDB__DatabaseName=GestionRecursosHumanosDB"
    networks:
      - default

networks:
  default:
    driver: bridge

